# Generated by Django 5.2.8 on 2025-12-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_number', models.IntegerField()),
                ('team1_score', models.IntegerField(default=0)),
                ('team2_score', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'games',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'game_genres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GamesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('has_heroes', models.BooleanField(default=False)),
                ('has_towers', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'games_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'heroes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'maps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'matches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MatchesHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('operation_type', models.CharField(max_length=10)),
                ('operation_timestamp', models.DateTimeField(null=True)),
                ('operation_user', models.TextField(null=True)),
                ('old_id', models.IntegerField(null=True)),
                ('old_stage_id', models.IntegerField(null=True)),
                ('old_team1_id', models.IntegerField(null=True)),
                ('old_team2_id', models.IntegerField(null=True)),
                ('old_winner_team_id', models.IntegerField(null=True)),
                ('old_match_date', models.DateField(null=True)),
                ('new_id', models.IntegerField(null=True)),
                ('new_stage_id', models.IntegerField(null=True)),
                ('new_team1_id', models.IntegerField(null=True)),
                ('new_team2_id', models.IntegerField(null=True)),
                ('new_winner_team_id', models.IntegerField(null=True)),
                ('new_match_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'matches_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.TextField(unique=True)),
                ('full_name', models.TextField(blank=True, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('role', models.TextField(blank=True, null=True)),
                ('total_winnings', models.IntegerField(default=0)),
                ('status', models.TextField(default='active')),
            ],
            options={
                'db_table': 'players',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'player_game_stats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayersHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('operation_type', models.CharField(max_length=10)),
                ('operation_timestamp', models.DateTimeField(null=True)),
                ('operation_user', models.TextField(null=True)),
                ('old_id', models.IntegerField(null=True)),
                ('old_nickname', models.TextField(null=True)),
                ('old_full_name', models.TextField(null=True)),
                ('old_birthdate', models.DateField(null=True)),
                ('old_country_id', models.IntegerField(null=True)),
                ('old_role', models.TextField(null=True)),
                ('old_total_winnings', models.IntegerField(null=True)),
                ('old_status', models.TextField(null=True)),
                ('new_id', models.IntegerField(null=True)),
                ('new_nickname', models.TextField(null=True)),
                ('new_full_name', models.TextField(null=True)),
                ('new_birthdate', models.DateField(null=True)),
                ('new_country_id', models.IntegerField(null=True)),
                ('new_role', models.TextField(null=True)),
                ('new_total_winnings', models.IntegerField(null=True)),
                ('new_status', models.TextField(null=True)),
            ],
            options={
                'db_table': 'players_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerTeam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'player_teams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('created_at', models.DateField(blank=True, null=True)),
                ('disbanded_at', models.DateField(blank=True, null=True)),
                ('coach', models.TextField(blank=True, null=True)),
                ('manager', models.TextField(blank=True, null=True)),
                ('total_earnings', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'teams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'team_locations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamsHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('operation_type', models.CharField(max_length=10)),
                ('operation_timestamp', models.DateTimeField(null=True)),
                ('operation_user', models.TextField(null=True)),
                ('old_id', models.IntegerField(null=True)),
                ('old_name', models.TextField(null=True)),
                ('old_created_at', models.DateField(null=True)),
                ('old_disbanded_at', models.DateField(null=True)),
                ('old_coach', models.TextField(null=True)),
                ('old_manager', models.TextField(null=True)),
                ('old_total_earnings', models.IntegerField(null=True)),
                ('old_game_id', models.IntegerField(null=True)),
                ('old_captain_id', models.IntegerField(null=True)),
                ('new_id', models.IntegerField(null=True)),
                ('new_name', models.TextField(null=True)),
                ('new_created_at', models.DateField(null=True)),
                ('new_disbanded_at', models.DateField(null=True)),
                ('new_coach', models.TextField(null=True)),
                ('new_manager', models.TextField(null=True)),
                ('new_total_earnings', models.IntegerField(null=True)),
                ('new_game_id', models.IntegerField(null=True)),
                ('new_captain_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'teams_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('tier', models.TextField(blank=True, null=True)),
                ('prize_pool', models.IntegerField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('max_number_of_teams', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tournaments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(blank=True, null=True)),
                ('earnings', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tournament_participants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TournamentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('stage_type', models.TextField()),
                ('bracket_type', models.TextField(default='no_type')),
                ('stage_order', models.IntegerField()),
            ],
            options={
                'db_table': 'tournament_stages',
                'managed': False,
            },
        ),
    ]
